#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASS';
  CREATE DATABASE $APP_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_USER;
  \connect $APP_DB_NAME $APP_DB_USER
  BEGIN;
    CREATE TABLE IF NOT EXISTS APPLICATION_USER (
      id INT NOT NULL PRIMARY KEY,
      name VARCHAR NOT NULL
    );
    CREATE SEQUENCE IF NOT EXISTS APPLICATION_USER_ID_SEQ OWNED BY APPLICATION_USER.ID;
  COMMIT;
EOSQL