spring:
  profiles:
    active: development
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/spring_boot_angular}
    username: ${DB_USERNAME:dbo_user}
    password: ${DB_PASSWORD:K95^eHcSRw8w}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
server:
  port: 8080
  servlet:
    context-path: /spring-boot-angular
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}